---
apiVersion: v1
kind: Template
metadata:
  name: fabric8-toggles-service
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: f8toggles
    name: f8toggles
  spec:
    replicas: 1
    selector:
      app: f8toggles
      deploymentconfig: f8toggles
    strategy:
      resources:
        limits:
          memory: 1Gi
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: f8toggles
          deploymentconfig: f8toggles
      spec:
        containers:
        - env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: f8toggles
                key: database.url
          - name: GITHUB_CLIENT_ID
            value: 1776877589a8e28f67d3
          - name: GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: f8toggles
                key: github.client.secret
          - name: GITHUB_CALLBACK_URL
            value: http://f8toggles/api/auth/callback                                              
          image: registry.devshift.net/fabric8-services/fabric8-toggles:${IMAGE_TAG}
          imagePullPolicy: Always
          name: f8toggles
          ports:
          - containerPort: 4242
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 4242
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 4242
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    name: f8toggles
  spec:
    ports:
      - protocol: TCP
        port: 80
        targetPort: 4242
    selector:
      deploymentconfig: f8toggles
parameters:
- name: IMAGE_TAG
  value: latest
